### ISSUE TITLE
Placeholder Text goes outside the bounds of the TextField

### ISSUE THREAD

**Issue by JamesSedlacek** [edgar-zigis/CocoaTextField#10]
When the placeholder text is long, it goes outside of the bounds of the textfield. 

I tried setting clipToBounds = true, but this doesn't work because of the animation & text outside of the textfield.

**Comment by edgar-zigis** [comment]
Hello, will look at it today.

**Comment by edgar-zigis** [comment]
Issue has been resolved, package is available on CocoaPods, Carthage and SPM.
